config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  resources :events, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end

  get "landhome", to: "menus#landhome"

  resources :events, only: %i[index new create show destroy]

  resources :profiles

  resources :bookings, only: :index

  resources :contacts, only: :index

  resources :events, only: :show do
    member do
      post :participation
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  GENDER = %w[Female Male Nonbinary Other]

  has_one_attached :photo, dependent: :destroy

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :find_profile, only: %i[show edit update]
  before_action :authenticate_user!
  # only profile owner can edit or update post
  # only signed in users can see show page of profile
  # only signed in users can see profile avatar in events show page

  def show
    @user = current_user
    @organizer = User.find(params[:id])
    @events = @organizer.events
    @profile = Profile.find(params[:id])
    @chatroom = Chatroom.find_by_users(@profile.user, current_user)
  end

  def edit
    @user = current_user
  end

  def update
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  private

  def find_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:id, :last_name, :username, :birthdate, :gender, :bio, :interests, :postcode, :city, :user_id, :photo)
  end
end

app/views/profiles/edit.html.erb
<div class="profile-edit">
  <h3>Edit your profile</h3>

  <div class="new-offer">
    <%= simple_form_for @profile, url: profile_path(@profile), html: { autocomplete: 'off' } do |f| %>
      <%= f.input :photo, as: :file %>
      <%= f.input :last_name %>
      <%= f.input :username %>
      <%= f.input :birthdate, as: :date, start_year: 1920,
                                  end_year: Date.today.year,
                                  selected: 1,
                                  order: [:day, :month, :year] %>
      <%= f.input :gender, as: :select, collection: Profile::GENDER, prompt: "Select your gender" %>
      <%= f.input :bio, as: :text %>
      <%= f.input :interests, as: :text %>
      <%= f.input :postcode, as: :integer %>
      <%= f.input :city %>
      <div class="mother-buttons">
      <%= f.submit "Confirm", class: "button-green" %>
    <% end %>
    <%= link_to "Cancel", profile_path(@profile), class: "button-red"   %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container profile-father">

    <div class="profile-card">
      <div class="profile-username">
      <% if @profile.username.present? %>
        <h4><%= @profile.username %></h4>
      <% end %>
    </div>

    <div class="profile-pic-show">
      <% if @profile.photo.present? %>
        <%= cl_image_tag @profile.photo.key, class:"profile-pic-square" %>
      <% else %>
        <%= image_tag "Default_pfp.jpg", alt: "Default Profile Picture", class:"profile-pic" %>
      <% end %>
    </div>

    <div class="profile-names">
      <%= @profile.user.first_name %>
      <% if @profile.last_name.present? %>
        <p><%= @profile.last_name[0] %>.</p>
      <% end %>
    </div>

    <div class="profile-info d-flex flex-direction-row">
      <% if @profile.birthdate.present? %>
        <div class="profile-age profile-text flex-grow-1 align-items-center">
          <% age = Time.now.year - @profile.birthdate.year - ((Time.now.month > @profile.birthdate.month || (Time.now.month == @profile.birthdate.month && Time.now.day >= @profile.birthdate.day)) ? 0 : 1) %>
          <p class="text-bold">Age: </p>
          <p class="text-normal"> <%= age %></p>
        </div>
      <% end %>
      <% if @profile.city.present? %>
        <div class="profile-city profile-text">
          <p class="text-normal"><i class="fa-solid fa-location-dot"></i> <%= @profile.city %></p>
        </div>
        <% end %>
    </div>


    <% if @profile.bio.present? %>
      <div class="profile-text text-long">
        <p class="text-bold">Bio</p>
        <%= @profile.bio %>
    <% end %>
    <% if @profile.interests.present? %>
        <p class="text-bold">Interests</p>
        <%= @profile.interests %>
      </div>
    <% end %>

  <% if @events.count == 1 %>
    <p>1 event created</p>
  <% else %>
    <p><%= @events.count %> events created</p>
  <% end %>
  <%# <div class="profile-events">
    <% @events.each do |event| %>
      <%# <%= cl_image_tag event.photo.key, class: "card-image", height: 70, width: 70,  crop: :fill  %>
      <%# <p> %>
        <%# <%= event.name %>
      <%# </p> %>
    <%# <% end %>
  <%# </div> %>

    <% if @profile.user == @user %>
        <%= link_to "Edit your profile", edit_profile_path(@profile), class:"btn chatedit" %>
    <% end  %>

    </div>



  <div class="chat">
      <% unless @profile == current_user.profile %>
      <% if @chatroom %>
        <div class="chat-message">
          <%= link_to "Message", chatroom_path(@chatroom), class:"btn chat-button" %>
        </div>
      <% else %>
        <div class="chat-message">
          <%= simple_form_for Chatroom.new do |f| %>
            <%= f.input :receiver_id, input_html: { class:"d-none", value: @profile.user.id } %>
            <%= f.input :sender_id, input_html: { class:"d-none", value: current_user.id } %>
              <%= f.submit "Start chat", class: "button-green" %>
          <% end %>
        </div>
      <% end %>
    <% end %>

  </div>


</div>