config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  resources :events, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end

  get "landhome", to: "menus#landhome"

  resources :events, only: %i[index new create show destroy]

  resources :profiles

  resources :bookings, only: :index

  resources :contacts, only: :index

  resources :events, only: :show do
    member do
      post :participation
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid d-flex justify-content-between">
    <!-- left arrow chevron here -->
    <%= link_to 'javascript:history.back()', class: 'navbar-prev-icon' do %>
      <i class="fa-sharp fa-solid fa-chevron-left fa-lg" style="color: #9723c9;"></i>
    <% end %>
    <!-- logo container -->
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-icon-purple.png", alt: "Home", class: "navbar-logo" %>
    <% end %>
    <!-- toggled menu -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-sharp fa-solid fa-bars" style="color: #9723c9;"></i>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto d-flex justify-content-center">
          <% if user_signed_in? %>
            <!-- profile dropdown -->
            <li class="nav-info dropdown">
              <li class="nav-info">
                <div class="d-flex justify-content-between align-items-center">
                <div class="avatar-container">
                  <div class="icon-avatar">
                    <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <% if current_user.profile.present? %>
                      <!-- profile avatar -->
                        <% if current_user.profile.photo.present? %>
                          <%= cl_image_tag current_user.profile.photo.key, alt: "Profile Picture", class: "navbar-image"%>
                        <% else %>
                          <%= image_tag "default_avatar.png", alt: "Default Profile Picture", class: "navbar-image" %>
                        <% end %>
                      <% end %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                      <%= link_to "Profile", profile_path(current_user.id), class: "dropdown-item" %>
                      <%= link_to "Edit Profile", edit_profile_path(current_user.id), class: "dropdown-item" %>
                    </div>
                  </div>
                </div>
                <!-- profile name and email -->
                  <div class="me-auto">
                  <div class="content-right">
                    <div class="font-name">
                      <%=current_user.first_name.capitalize%>
                    </div>
                    <div class="font-email">
                      <%=current_user.email%>
                    </div>
                  </div>
                  </div>
                </div>
              </li>
            </li>
          <div class="navbar-link">
            <!-- homepage -->
            <li class="nav-item">
              <div class="d-flex justify-content-between align-items-center">
                <div class="icon-left">
                  <i class="fa-solid fa-house fa-xl" style="color: #9723c9;"></i>
                </div>
                <div class="me-auto">
                <div class="content-right">
                  <%= link_to "Home", landhome_path, class: "nav-link" %>
                </div>
                </div>
            </li>
            <!-- dashboard -->
            <li class="nav-item">
              <div class="d-flex justify-content-between align-items-center">
                <div class="icon-left">
                  <i class="fa-solid fa-table-columns fa-xl" style="color: #9723c9;"></i>
                </div>
                <div class="me-auto">
                <div class="content-right">
                  <%= link_to "Dashboard", bookings_path, class: "nav-link" %>
                </div>
                </div>
              </div>
            </li>
            <!-- find events -->
            <li class="nav-item active">
              <div class="d-flex justify-content-between align-items-center">
                <div class="icon-left">
                  <i class="fa-solid fa-magnifying-glass-location fa-xl" style="color: #9723c9;"></i>
                </div>
                <div class="me-auto">
                <div class="content-right">
                  <%= link_to "Find Events", search_events_path, class: "nav-link" %>
                </div>
                </div>
              </div>
            </li>
            <!-- create events -->
            <li class="nav-item">
              <div class="d-flex justify-content-between align-items-center">
                <div class="icon-left">
                  <i class="fa-regular fa-calendar-plus fa-xl" style="color: #9723c9;"></i>
                </div>
                <div class="me-auto">
                <div class="content-right">
                  <%= link_to "Create Events", new_event_path, class: "nav-link" %>
                </div>
                </div>
              </div>
            </li>
           <!-- our contacts -->
            <li class="nav-item">
              <div class="d-flex justify-content-between align-items-center">
                <div class="icon-left">
                  <i class="fa-solid fa-hand-holding-hand fa-xl" style="color: #9723c9;"></i>
                </div>
                <div class="me-auto">
                <div class="content-right">
                  <%= link_to "The creators", contacts_path, class: "nav-link" %>
                </div>
                </div>
              </div>
            </li>
            <!-- log out -->
            <li class="nav-item">
               <div class="d-flex justify-content-between align-items-center">
                <div class="icon-left">
                  <i class="fa-solid fa-right-from-bracket fa-xl" style="color: #9723c9;"></i>
                </div>
                <div class="me-auto">
                <div class="content-right">
                  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
                </div>
                </div>
              </div>
            </li>
        <!-- if user is signed out starts here -->
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
          </div>
        </ul>
      </div>
  </div>
</div>