config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  resources :events, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end

  get "landhome", to: "menus#landhome"

  resources :events, only: %i[index new create show destroy]

  resources :profiles

  resources :bookings, only: :index

  resources :contacts, only: :index

  resources :events, only: :show do
    member do
      post :participation
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  # belongs_to :user
  belongs_to :organizer, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, dependent: :destroy
  has_many :bookings
  has_many :users, through: :bookings
  has_one_attached :photo, dependent: :destroy
  enum age_group: { children: 0, teenagers: 1, young_adults: 2, middle_aged: 3, adults: 4, seniors: 5, all_ages: 6 }

  validates :name, presence: true
  # validates :description, presence: true, length: { maximum: 200 }
  validates :time, presence: true
  # validates :price, numericality: { greater_than: 0.00, message: "Price cannot be lesser than 0" }
  CATEGORY = %w[Music Comedy Art Food Drinks Market Help Lesson Party Gardening Literature Sports Pets Religion Film Babies Housesitting Weird Other]

  def self.price_ranges(step)
    ranges = []
    start = 0
    while start < 50 # Adjust the maximum price as needed
      ranges << ["#{start + 1}-#{start + step}€", start + 1..start + step ]
      start += step
    end
    ranges << ["50-100€", 50..100]
    ranges.unshift(["Free", 0])
    ranges
  end

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  scope :with_category, ->(category) { where(category: category) if category.present? }
  scope :with_age_group, ->(age_group) { where(age_group: age_group) if age_group.present? }
  scope :with_price, ->(price) { where(price: price) if price.present? }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[participation show edit update destroy]

  def index

    postcode = params[:search][:postcode]
    city = params[:search][:city]

    if postcode.present?
      # Validate that postcode is exactly 5 digits
      if postcode.match?(/\A\d{5}\z/)
        if city.present?
          @events = Event.where("address ILIKE ? AND address ~ ?", "%#{city}%", "\\m#{postcode}\\M")
        else
          @events = Event.where("address ~ ?", "\\m#{postcode}\\M")
        end

        if params[:category].present?
          @events = @events.with_category(params[:category])
        end

        if params[:age_group].present?
          @events = @events.with_age_group(params[:age_group])
        end

        if params[:price].present?
          if params[:price] == "0"
            @events = @events.with_price(params[:price])
          else
            prices = params[:price].split("..").map {|number| number.to_f}
            @events = @events.where(price: prices[0]..prices[1])
          end
        end

        @price_ranges = Event.price_ranges(10)

        @markers = @events.geocoded.map do |event|
          {
            lat: event.latitude,
            lng: event.longitude,
            info_window_html: render_to_string(partial: "info_window", locals: { event: event }, formats: :html )
          }
        end

        respond_to do |format|
          format.html
          format.json
        end

      else
        flash[:alert] = "Postcode must be 5 digits"
        redirect_to search_events_path and return
      end
    else
      flash[:alert] = "Postcode is required"
      redirect_to search_events_path and return
    end
  end

  def new
    @event = Event.new
  end

  def participation
    @user = current_user
    @booking = Booking.new(user: @user, event: @event)
    if @booking.save
      redirect_to event_path(@event)
    else
      redirect_to event_path(@event), flash: {error: "Cannot save the booking!"}
    end
  end

  def create
    @event = Event.new(event_params)
    @event.organizer = current_user
    if @event.save
      redirect_to event_path(@event), notice: 'Offer was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, status: :see_other
  end

  def show
    @booking = Booking.find_by(event: @event, user: current_user)
    @bookings = @event.bookings
    @participants = @event.users
    @comments = @event.comments
    @comment = Comment.new
    @profile = current_user.profile
    @organizer = @event.organizer
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params[:event][:age_group] = params[:event][:age_group].to_i
    params.require(:event).permit(:name, :description, :address, :age_group, :date, :time, :category, :price, :photo)
  end

end

app/views/events/_events.html.erb
<div data-controller="filters">
  <div style="width: 100%; height: 400px;"
    class="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="events-content">
    <p class="events-text-purple">Filter Events</p>
    <div class="dropdown-row d-flex flex-direction-row">
      <div class="dropdown-filters">
        <%= form_with(url: events_path, method: :get, class: "form-row",
                      data: {
                        # turbo_frame: "filter_results",
                        # turbo_action: "advance",
                      }) do |form| %>
            <%= form.select :category, Event::CATEGORY, { prompt: "Category" }, { data: { action: "change->filters#updateEvents" } } %>

            <%= form.select :age_group, Event.age_groups.collect{|key, value| [key.to_s.titleize, value]}, {prompt: "Age Group" }, { data: { action: "change->filters#updateEvents" } } %>

            <%= form.select :price, @price_ranges, { prompt: "Price" }, { data: { action: "change->filters#updateEvents" } } %>
        <% end %>
      </div>
    </div>
    <div class="button-father">
      <button class="button-reset" type="reset", data-action="click->filters#updateEvents">
        Reset
      </button>
    </div>

    <div >
      <% if @events.present? %>
        <p class="events-text"><%= @events.count %> events found</p>
        <% @events.each do |event| %>
          <div class="event-cards">
            <div class="event-pic d-flex align-items-center">
              <% if event.photo.attached? %>
                <%= cl_image_tag event.photo.key, class: "card-image", height: 110, width: 110,  crop: :fill %>
              <% else %>
                <%= image_tag "event.jpg", alt: "event-default", width: 200 %>
              <% end %>
            </div>
            <div class="text-container" >
              <h2><%= link_to event.name, event_path(event), class: "link-underline-opacity-0" %></h2>
              <div>
                <i class="fa-solid fa-location-dot"></i>
                <%= event.address %>
              </div>
              <div class="">
                <% if event.date.present? %>
                  <i class="fa-regular fa-calendar-days"></i>
                  <%= event.date.strftime("%A, %B %d, %Y") %>
                <% end %>
              </div>
              <div>
                <% if event.time.present? %>
                  <i class="fa-regular fa-clock"></i>
                  <%= event.time.strftime("%I:%M %p") %>
                <% end %>
              </div>
              <div class="d-flex flex-direction-row">
                <div class="category-box d-flex flex-grow-1 align-items-center">
                  <i class="fa-solid fa-list"></i> <%= event.category %>
                </div>
                <div class="age-box d-flex flex-grow-1 align-items-center">
                  <i class="fa-solid fa-people-group"></i> <%= age_group_to_string(event) %>
                </div>
              </div>
            </div>

            <div class="price-box">
              <% if event.price == 0 %>
                <p class="price-green">Free</p>
              <% else %>
                <p class="price-purple">
                  <%= number_to_currency(event.price, unit: "€") %>
                </p>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>There is no event in this city</p>
      <% end  %>
    </div>
  </div>

</div>

app/views/events/_info_window.html.erb
<div>
  <h2><%= event.name %></h2>
  <div class="popup-text">
    <p><%= event.address %></p>
    <p class="category-bold"><%= event.category %></p>
  </div>
</div>

app/views/events/edit.html.erb
<div class="edit-event">
  <h2>Do you need to make some changes to your event?</h2>

  <div class="new-offer">
    <%= simple_form_for @event, html: { multipart: true, autocomplete: 'off'  } do |f| %>
      <%= f.input :name, { class: "label-dark" }%>
      <%= f.input :description %>
      <%= f.input :address, presence: true, format: { with: /\A([^<>{}\\]|\s)+\z/, message: "Address can't be blank or contain special characters <>, {, }, or \" " } %>
      <%= f.input :age_group, collection: Event.age_groups.collect{|key, value| [key.to_s.titleize, value]}, as: :select, prompt: "Select an age group for your event" %>
      <%= f.input :date, as: :string, input_html: {data: {controller: "datepicker"}} %>
      <%= f.input :time %>
      <%= f.input :category, collection: Event::CATEGORY, as: :select, prompt: "Select a category" %>
      <%= f.input :price %>
      <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
  </div>

  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<%= render "events" %>

app/views/events/new.html.erb
<div class="form-new p-5">
  <h1>Your new Event!</h1>

  <div class="new-offer">
    <%= simple_form_for @event, html: { multipart: true, autocomplete: 'off'  } do |f| %>
      <div>
        <%= f.input :name, { class: "label-dark",  placeholder: "Name of event" } %>
      </div>
      <div>
        <%= f.input :description, placeholder: "Your description here (max. 250 characters)...", class: "textarea-box" %>
      </div>
      <div>
        <%= f.input :address, presence: true, placeholder: "Address (street, number, postcode, city)", format: { with: /\A([^<>{}\\]|\s)+\z/, message: "Address can't be blank or contain special characters <>, {, }, or \" " } %>
      </div>
      <div>
        <%= f.input :photo, as: :file %>
      </div>
      <div>
        <%= f.input :age_group, collection: Event.age_groups.collect{|key, value| [key.to_s.titleize, value]}, as: :select %>
      </div>
      <div>
        <%= f.input :date, as: :string, input_html: {data: {controller: "datepicker"}} %>
      </div>
      <div>
        <%= f.input :time %>
      </div>
      <div>
        <%= f.input :category, collection: Event::CATEGORY, as: :select, prompt: "Select a category" %>
      </div>
      <div>
        <%= f.input :price, placeholder: "00.00" %>
      </div>
      <div class="mother-buttons">
        <%= f.submit "Confirm", class: "button-green" %>
      <% end %>
      <%= link_to "Cancel", landhome_path, class: "button-red" %>
      </div>
  </div>
  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/events/search.html.erb
<style>
  .navbar {
    display: none;
  }
</style>

<div class="search-page">

    <h1 class="search-text">Spot your nearest event</h1>

    <%= simple_form_for :search, url: events_path, method: :get, html: { class: 'search-form', autocomplete: 'off' } do |f| %>
    <div>
      <%= f.input :postcode, placeholder: "E.g. 10115", input_html: { class: "form-control custom-input", required: true, pattern: "\\d{5}", title: "Postcode must be 5 digits" } %>
    </div>

    <div>
      <%= f.input :city, placeholder: "E.g. Berlin", input_html: { class: "form-control custom-input" } %>
    </div>

    <div>
      <%= f.button :submit, "Search", class: "btn landhome-yellow-buttons" %>
    </div>
    <div class="search-yellow-button">
      <%= link_to "Back to menu", landhome_path, class: "btn landhome-yellow-buttons" %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="event-show">

  <% if @event.photo && @event.photo.key %>
    <div class="card-category"style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
            url('<%= cl_image_path @event.photo.key, class:"show-img" %>')"></div>
  <% else %>
    <div class="card-category">
      <%= image_tag "event.jpg", alt: "train", width: 200 %>
    </div>

  <% end %>


  <div class="event-content">

    <div class="event-card">
      <div class="card-top">
        <h1><%= @event.name %></h1>
        <div class="price">
          <% if @event.price == 0 %>
            <p>Free</p>
          <% else %>
            <%= number_to_currency(@event.price, unit: "€") %>
          <% end %>
        </div>
      </div>


      <div class="event-data">
        <div class="red-dot"></div>
        <p>Location: <%= @event.address %></p>
      </div>

      <div class="event-data">
        <div class="red-dot"></div><p><%= @event.date.strftime("%A, %B %d, %Y") %></p>
      </div>

      <div class="event-data">
        <div class="red-dot"></div><p>Time: <%= @event.time.strftime("%I:%M %p") %></p>
      </div>

      <div class="event-image">
        <% if @organizer.present? %>
          <% if current_user == @organizer  %>
            <% if @profile.photo.present? %>
              <%= cl_image_tag(@profile.photo.key, class:"d-block", class: "carrousel-image") %>
            <% else %>
              <%= image_tag "default_avatar.png", class:"d-block", alt: "Default Profile Picture", class: "carrousel-image" %>
            <% end %>
            <p class="youcreator">You</p>
          <% else %>
            <% if @profile.photo.present? %>
              <%= cl_image_tag(@organizer.profile.photo.key, class:"d-block", class: "carrousel-image") %>
              <p><%= link_to @organizer.first_name, profile_path(@organizer.profile), class:"organizer-text" %></p>
            <%# <% else %>
              <%# <%= image_tag "default_avatar.png", class:"d-block", alt: "Default Profile Picture", class: "organizer-img" %>
              <%# <p><%= link_to @organizer.first_name, profile_path(@organizer.profile), class:"organizer-text"</p> %>
            <% end %>
            <p class="image-text">is the host </p>
          <% end %>
        <% end %>
      </div>

    </div>
    <div class="event-card">
       <p class="image-text">Description: </p>
       <%= @event.description %>
    </div>


    <% if @booking.nil? %>
      <% disabled = "" %>
    <% else %>
        <% disabled = "disabled" %>
      <% end %>


  <% if @organizer.present? %>
    <% if current_user == @organizer  %>

      <% if @profile && @profile.photo.present? %>
        <%= cl_image_tag(@organizer.profile.photo.key, class:"d-none", style: "width: 50px; height: 50px;") %>
      <% else %>
        <%= image_tag "default_avatar.png", class:"d-block", alt: "Default Profile Picture", class: "navbar-image" %>
      <% end %>
      <p class="d-none">You</p>
    <% else %>

    <% end %>

    <div class="edit-delete">
      <% if @event.organizer == current_user %>
        <i class="fa-solid fa-trash ">
          <%= link_to "Delete",
          event_path(@event),
          data: {turbo_method: :delete, turbo_confirm: "Oh no! Are you sure?"}, class:"delete-event"%>
        </i>
        <% end %>
      <% if @event.organizer == current_user %>
        <i class="fa-solid fa-file-pen">
        <%= link_to "Edit", edit_event_path(@event), class: "show-edit"%></i>
      <% end %>
        <% end %>

    </div>




<!-- CAROUSEL -->
<h2 class="events-headers">Who else already joined? </h2>
<% if @participants.present? %>
  <div id="participantsCarousel" class="carousel slide" data-ride="carousel" >
    <div class="carousel-inner">
      <% @participants.reverse.in_groups_of(3, false).each_with_index do |group, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <div class="d-flex justify-content-around">
            <% group.each do |user|  %>
              <div class="avatar">
                <%#  @event.users.each do |user| %>
                <% if user.profile && user.profile.photo.present? %>
                  <%= cl_image_tag user.profile.photo.key, class:"d-block card-img" %>
                  <%= link_to user.first_name, profile_path(user.profile), class:"name-card"  %>
                <% else %>
                  <%= image_tag "Default_pfp.jpg", class:"d-block carrousel-image", alt: "Default Profile Picture" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- Left and right controls -->
    <button class="carousel-control-prev" type="button" data-bs-target="#participantsCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#participantsCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<% end %>
<!-- CAROUSEL -->

<div class="event-buttons">
  <%= link_to "Back to search", search_events_path(@event), class:"btn-search"%>
  <%= button_to "Book Now!", participation_event_path(@event), data: {turbo_method: 'post', bs_toggle: "modal", bs_target: "#exampleModal" }, class:"btn-participate", disabled: @event.users.include?(current_user) %>
</div>


  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header border-0">
          <h1 class="modal-title fs-0" id="exampleModalLabel">Awesome!</h1>
        </div>
        <div class="modal-body">
          <p>You are successfully registered, see you there!</p>
        </div>
        <div class="modal-footer border-0">
          <button type="button" class="btn btn-secondary show-button-ok-thanks" data-bs-dismiss="modal"><%= link_to "Ok, Thanks", event_path(@event), class:"btn" %></button>
          <%= link_to "Go to dashboard", bookings_path, class:"a-link" %>
        </div>

      </div>
    </div>
  </div>






<!-- Comments -->

  <div class="comments">
    <h1 class="events-headers">Post Something:</h1>
    <div class="comments-input">
      <%= simple_form_for [@event, @comment] do |f| %>
        <%= f.input :content %>
        <%= f.submit "Send", class: "btn-comments" %>
      <% end %>
    </div>

</div>
<div class="comments-view">
  <ul>
    <% @comments.each do |c| %>
    <div class="items-comments">
      <div class="commenter">
        <%= cl_image_tag(c.user.profile.photo.key, class:"d-block comments-img") %>
        <div class="comments-text">
          <%= link_to c.user.first_name, profile_path(c.user.profile), class:"comment-name"  %>

        </div>
      </div>
      <p><%= c.content %></p>
    </div>
    <% end %>
  </ul>

</div>
</div>
</div>